name: Sync Commits to repoB

on:
  push:
    branches:
      - main # Укажите нужную ветку, если это не main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repoA
      uses: actions/checkout@v3
      with:
        repository: FFrein/repoA
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: main # Укажите нужную ветку, если это не main

    - name: Setup Git
      run: |
        git config user.name "FFrein"
        git config user.email "pesetsky2003g@gmail.com"

    - name: Clone repoB
      run: |
        git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/FFrein/repoB.git
        cd repoB

    - name: Sync commits to repoB
      run: |
        cd repoB
        git remote add repoA https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/FFrein/repoA.git
        git fetch repoA
        git checkout main
        git reset --hard repoA/main
        git push origin main --force
