name: Sync Commits to repoB

on:
  push:
    branches:
      - main # Укажите нужную ветку, если это не main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repoA
      uses: actions/checkout@v3
      with:
        repository: FFrein/repoA
        token: ${{ secrets.PAT }}
        ref: main # Укажите нужную ветку, если это не main

    - name: Setup Git
      run: |
        git config --global user.name "FFrein"
        git config --global user.email "pesetsky2003g@gmail.com"

    - name: Clone repoB
      run: |
        git clone https://x-access-token:${{ secrets.PAT }}@github.com/FFrein/repoB.git
        cd repoB

    - name: Remove unwanted folder
      run: |
        rm -rf ../repoA/.github/workflows # Удалите папку `workflows` из `repoA`

    - name: Sync commits to repoB
      run: |
        cd repoB
        git remote add repoA https://x-access-token:${{ secrets.PAT }}@github.com/FFrein/repoA.git
        git fetch repoA

        # Iterate over each commit from repoA and reapply it with a new author
        git filter-branch --env-filter '
          if [ "$GIT_COMMIT" != "" ]; then
            export GIT_AUTHOR_NAME="FFrein"
            export GIT_AUTHOR_EMAIL="pesetsky2003g@gmail.com"
            export GIT_COMMITTER_NAME="FFrein"
            export GIT_COMMITTER_EMAIL="pesetsky2003g@gmail.com"
          fi' -- --all

        git checkout main
        git reset --hard repoA/main
        git push origin main --force
